apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wgih7mo3c-java-springboot
  janus-idp.io/tekton: wgih7mo3c-java-springboot
  backstage.io/kubernetes-id: wgih7mo3c-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wgih7mo3c-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
